version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: telegram_postgres
    environment:
      POSTGRES_DB: telegram_data
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 4124
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
